export const LANGUAGE_MAP: Record<string, string> = {
  Afrikaans: 'afrikaans',
  Arabic: 'arabic',
  Armenian: 'armenian',
  ASL: 'asl',
  Bengali: 'bengali',
  Bosnian: 'bosnian',
  Cantonese: 'cantonese',
  Czech: 'czech',
  Dutch: 'dutch',
  English: 'english',
  Farsi: 'farsi',
  French: 'french',
  German: 'german',
  Greek: 'greek',
  'Haitian Creole': 'haitian_creole',
  Hebrew: 'hebrew',
  Hindi: 'hindi',
  Hmong: 'hmong',
  Hungarian: 'hungarian',
  Indonesian: 'indonesian',
  Iranian: 'iranian',
  Italian: 'italian',
  Japanese: 'japanese',
  Javanese: 'javanese',
  Korean: 'korean',
  Mandarin: 'chinese',
  Norwegian: 'norwegian',
  Other: 'other',
  Patois: 'patois',
  Polish: 'polish',
  Portuguese: 'portuguese',
  Punjabi: 'punjabi',
  Romanian: 'romanian',
  Russian: 'russian',
  Spanish: 'spanish',
  Suzhou: 'suzhou',
  Swahili: 'swahili',
  Swedish: 'swedish',
  Tagalog: 'filipino',
  Thai: 'thai',
  Turkish: 'turkish',
  Ukrainian: 'ukrainian',
  Urdu: 'urdu',
  Vietnamese: 'vietnamese',
  Yoruba: 'yoruba',
  "My selection isn't listed": 'not_listed',
}

export const GENDER_MAP: Record<string, string> = {
  Agender: 'agender',
  Bigender: 'bigender',
  Cis: 'cis',
  Female: 'female',
  'Gender fluid': 'gender_fluid',
  Male: 'male',
  "My gender isn't listed": 'not_listed',
  'Non-binary': 'non_binary',
  'Prefer not to respond': 'prefer_not_to_respond',
  Trans: 'trans',
}

export const RACE_MAP: Record<string, string> = {
  'American Indian or Alaska Native': 'american_indian_or_alaska_native',
  Asian: 'asian',
  'Biracial or Multiracial': 'biracial_or_multiracial',
  'Black or African American': 'black_or_african_american',
  'Caucasian or White': 'caucasian_or_white',
  'Hispanic or Latinx': 'hispanic_or_latinx',
  'Middle Eastern': 'middle_eastern',
  'Native Hawaiian or Other Pacific Islander': 'native_hawaiian_or_other_pacific_islander',
  Other: 'other',
  'Prefer Not to Respond': 'prefer_not_to_respond',
  'South East Asian': 'south_east_asian',
}

// Maps UI specialization labels to the API's short lowercase keys.
// Deprecated as of spec v0.25.1 (still accepted, no longer supported for filtering):
// chronic_impulsivity, chronic_relapse, drug_abuse, impulsivity, job_stress,
// legal_stress, military_and_veterans, racial_trauma.
export const SPECIALIZATION_MAP: Record<string, string> = {
  Addiction: 'addiction',
  ADHD: 'adhd',
  Adoption: 'adoption',
  Aging: 'aging',
  'Alcohol Use': 'alcohol_use',
  "Alzheimer's": 'alzheimers',
  'Anger Management': 'anger_management',
  'Antisocial Personality': 'antisocial_personality',
  Anxiety: 'anxiety',
  "Autism or Asperger's Syndrome": 'autism_or_aspergers',
  'Behavioral Issues': 'behavioral_issues',
  'Bipolar Disorder': 'bipolar_disorder',
  'Borderline Personality': 'borderline_personality',
  'Career Counseling': 'career_counseling',
  'Child Abuse or Neglect': 'child_abuse_or_neglect',
  'Chronic Illness': 'chronic_illness',
  'Chronic Impulsivity': 'chronic_impulsivity',
  'Chronic Pain': 'chronic_pain',
  'Chronic Relapse': 'chronic_relapse',
  Codependency: 'codependency',
  'Coping Skills': 'coping_skills',
  'Cultural Stress': 'cultural_stress',
  'Depersonalization/Derealization (DPDR)': 'depersonalization_derealization',
  Depression: 'depression',
  'Developmental Disorders': 'developmental_disorders',
  'Dissociative Disorders': 'dissociative_disorders',
  Divorce: 'divorce',
  'Domestic Violence': 'domestic_violence',
  'Drug Abuse': 'drug_abuse',
  'Eating Disorders': 'eating_disorders',
  'Family Conflict': 'family_conflict',
  'First Responders': 'first_responders',
  Gambling: 'gambling',
  'Gender Identity': 'gender_identity',
  Grief: 'grief',
  Hoarding: 'hoarding',
  'Impulse Control Disorders': 'impulse_control_disorders',
  Impulsivity: 'impulsivity',
  Infertility: 'infertility',
  Infidelity: 'infidelity',
  'Intellectual Disability': 'intellectual_disability',
  'Internet Addiction': 'internet_addiction',
  'Job Stress': 'job_stress',
  'Learning Disabilities': 'learning_disabilities',
  'Legal Stress': 'legal_stress',
  'LGBTQIA+': 'lgbtqia',
  'Life Transitions': 'life_transitions',
  "Men's Issues": 'mens_issues',
  'Military and Veterans': 'military_and_veterans',
  'Mood Disorders': 'mood_disorders',
  'Obsessive-Compulsive (OCD)': 'obsessive_compulsive',
  'Older Adult': 'older_adult',
  'Older Adults': 'older_adult',
  'Oppositional Defiance': 'oppositional_defiance',
  'Panic Attacks': 'panic_attacks',
  Parenting: 'parenting',
  'Peer Relationships': 'peer_relationships',
  'Personality Disorders': 'personality_disorders',
  'Pregnancy, Prenatal, Postpartum': 'pregnancy_prenatal_postpartum',
  Psychosis: 'psychosis',
  'Racial Identity': 'racial_identity',
  'Racial Trauma': 'racial_trauma',
  'Relapse Prevention': 'relapse_prevention',
  'Relationship Issues': 'relationship_issues',
  Schizophrenia: 'schizophrenia',
  'School Issues': 'school_issues',
  'Self Esteem': 'self_esteem',
  'Self-Harming': 'self_harming',
  'Sex Therapy': 'sex_therapy',
  'Sexual Abuse': 'sexual_abuse',
  'Sexual Addiction': 'sexual_addiction',
  'Sleep or Insomnia': 'sleep_or_insomnia',
  Spirituality: 'spirituality',
  'Sports Performance': 'sports_performance',
  Stress: 'stress',
  'Substance Use': 'substance_use',
  'Suicidal Ideation': 'suicidal_ideation',
  'Thought Disorders': 'thought_disorders',
  'Transgender Issues': 'transgender_issues',
  'Trauma and PTSD': 'trauma_and_ptsd',
  'Traumatic Brain Injury': 'traumatic_brain_injury',
  'Video Game Addiction': 'video_game_addiction',
  'Weight Loss': 'weight_loss',
  "Women's Issues": 'womens_issues',
}
