/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/insurances': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List of insurances Rula accepts
     * @description Returns a list of insurance carriers accepted by Rula, optionally filtered by state. Each insurance entry includes the carrier display name, network name, state, coverage type, and a unique id that can be used to reference the carrier in other API calls.
     */
    get: operations['insurancesIndex']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/providers/{uuid}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Information for a specific provider. */
    get: operations['providersShow']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/providers/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Search for providers matching criteria, returns summary information. */
    post: operations['providersSearch']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/providers/slots': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Available slots for a specific provider. */
    get: operations['providersSlots']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/patients': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Creates a patient for Rula
     * @description Creates a patient for Rula
     */
    post: operations['patientCreate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/patients/{uuid}/appointments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Information for a specific patient's appointments. */
    get: operations['patientAppointments']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/appointments/{uuid}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Retrieve info for an existing appointment */
    get: operations['appointmentsShow']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/appointments/{uuid}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Cancel an existing appointment */
    put: operations['appointmentsCancel']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/appointments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create an appointment */
    post: operations['appointmentsCreate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Appointment: {
      /** @description The unique identifier for the appointment */
      appointment_id: components['schemas']['Uuid']
      /** @description The unique identifier for the provider */
      provider_id: components['schemas']['Uuid']
      /**
       * Format: date-time
       * @description The UTC timestamp of the appointment start time
       */
      start_time: string
      /**
       * Format: date-time
       * @description The UTC timestamp of the appointment end time
       */
      end_time: string
      /**
       * @description The status of the appointment
       * @enum {string}
       */
      status: 'held' | 'confirmed' | 'canceled' | 'completed'
      /**
       * @description The location type of the appointment (telemedicine or in_person). Note: this is distinct from the therapy modality (Individual, Couples, etc.) which is captured in therapy_type.
       * @enum {string}
       */
      appointment_type: 'telemedicine' | 'in_person'
      /**
       * @description The therapy type the appointment is for
       * @enum {string}
       */
      therapy_type: 'individual' | 'family' | 'couples' | 'psychiatric'
    }
    /** Format: uuid */
    Uuid: string
    RequestValidationError: {
      /** @example Invalid request */
      message: string
      errors?: {
        /**
         * @description The field that failed validation
         * @example querystring.uuid
         */
        field: string
        /**
         * @description Description of the validation failure
         * @example must match pattern \"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$\"
         */
        message: string
      }[]
    }
    InternalServerError: {
      /** @example Internal Server Error */
      message: string
      /** @description The trace ID for the error */
      trace_id?: string
    }
    UnprocessableEntityError: {
      /** @example Unprocessable Entity */
      message: string
    }
    BadGatewayError: {
      /** @example Bad Gateway */
      message: string
      /** @description The trace ID for the error */
      trace_id?: string
    }
    NotFoundError: {
      /** @example Not Found */
      message: string
    }
    NotAcceptableError: {
      /** @example Not Acceptable */
      message: string
    }
    ConflictError: {
      /** @example Conflict */
      message: string
    }
  }
  responses: {
    /** @description Default Response */
    AppointmentsCreateResponse: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          appointment_id: string
          /**
           * @description The booking status of the appointment. "held" is returned when an appointment is first created. "confirmed" indicates the appointment has been fully confirmed.
           * @enum {string}
           */
          status: 'confirmed' | 'held'
        }
      }
    }
    /** @description Default Response */
    PatientCreateResponse: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description The Rula-assigned UUID for the patient. Use this in subsequent API calls (e.g. POST /v1/appointments, GET /v1/patients/{uuid}/appointments). */
          patient_id: string
          /** @description The patient's identifier from your system, echoed back from the request. */
          partner_patient_id: string
        }
      }
    }
    /** @description Appointment details retrieved successfully */
    AppointmentShowResponse: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Appointment']
      }
    }
    /** @description Default Response */
    PatientAppointmentsResponse: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description List of appointments belonging to the patient */
          appointments: components['schemas']['Appointment'][]
        }
      }
    }
    /** @description Default Response */
    ProvidersSearchResponse: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description List of providers matching the search criteria */
          providers: {
            /** @description The unique identifier for the provider */
            id: components['schemas']['Uuid']
            /** @description The provider's first name */
            first_name: string
            /** @description The provider's last name */
            last_name: string
            /** @description URL to the provider's profile image */
            profile_image_url?: string
            /** @description A brief biography of the provider */
            profile_bio?: string
            /** @description The genders the provider identifies with */
            genders?: string[]
            /** @description The races or ethnicities the provider identifies with */
            races?: string[]
            /**
             * Format: date-time
             * @description The start time of the provider's earliest available slot.
             */
            slot_start_time?: string
          }[]
        }
      }
    }
    /** @description Default Response */
    InsurancesIndexResponse: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description List of insurances Rula accepts */
          insurances: {
            /**
             * @description The unique identifier for the insurance carrier. Use this to uniquely reference a specific carrier across API calls such as the POST /v1/patients endpoint.
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string
            /**
             * @description Human-readable name of the insurance carrier, suitable for displaying to end users.
             * @example Aetna
             */
            carrier_display_name: string
            /**
             * @description The insurance network name. Use this value in the insurance field when searching for providers via POST /v1/providers/search. The value is case-insensitive.
             * @example aetna
             */
            network_name: string
            /**
             * @description Two-letter state code indicating which state this insurance is accepted in.
             * @example CA
             */
            state: string
            /**
             * @description The type of insurance coverage.
             * @example commercial
             * @enum {string}
             */
            coverage_type:
              | 'commercial'
              | 'eap'
              | 'HMO'
              | 'medicaid'
              | 'medicare_advantage'
              | 'medicare_ffs'
          }[]
        }
      }
    }
    /** @description Default Response */
    ProvidersShowResponse: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description The unique identifier for the provider */
          id: components['schemas']['Uuid']
          /** @description The provider's first name */
          first_name: string
          /** @description The provider's last name */
          last_name: string
          /** @description URL to the provider's profile image */
          profile_image_url?: string
          /** @description A brief biography of the provider */
          profile_bio?: string
          /** @description Summary of the provider's profile */
          profile_summary?: string
          /** @description Introduction to potential patients, high level overview of approach and background */
          profile_approach?: string
          /** @description Area of focus for provider. Helps align patient that best fits provider */
          profile_focus?: string
          /** @description Provider's journey to become a therapist. Helps patients understand motivations, signal of whether there's a fit in terms of lived experience */
          profile_journey?: string
          /** @description Goals for patients, helps with patient alignment */
          profile_goals?: string
          /** @description Expectations for the first session */
          profile_first_session?: string
          /**
           * @description String representation of the provider's role
           * @enum {string}
           */
          role_string?: 'Therapist' | 'Prescriber' | 'Unknown'
          /** @description List of insurances accepted by the provider */
          insurances?: string[]
          /** @description List of two-letter state codes for the states the provider is active in */
          active_states?: string[]
          /** @description Criteria of patients the provider is willing to see */
          willing_to_see?: (
            | 'adults'
            | 'children'
            | 'minors'
            | 'preteen'
            | 'individuals'
            | 'couples'
            | 'families'
          )[]
        }
      }
    }
    /** @description Default Response */
    ProvidersSlotsResponse: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description List of slots available for the provider */
          slots: {
            /** @description The unique Rula-provided identifier for the provider */
            provider_id: components['schemas']['Uuid']
            /**
             * @description Duration of the slot in minutes
             * @example 45
             */
            duration_mins: number
            /**
             * @description The location type of the slot
             * @enum {string}
             */
            location: 'in_person' | 'telemedicine'
            /**
             * @description Whether the slot is for a first appointment ("initial") or a subsequent session ("followup").
             * @enum {string}
             */
            series_type: 'initial' | 'followup'
            /**
             * Format: date-time
             * @description The ISO 8601 formatted start time of the slot
             * @example 2024-01-15T10:00:00Z
             */
            start_time_iso: string
          }[]
        }
      }
    }
  }
  parameters: never
  requestBodies: {
    AppointmentCancelRequest: {
      content: {
        'application/json': {
          /**
           * @description Who initiated the cancellation. Currently only "patient" is supported.
           * @enum {string}
           */
          initiator: 'patient'
          /** @description Freeform text detailing why the appointment was cancelled. */
          cancellation_reason_text: string
        }
      }
    }
    AppointmentsCreateRequest: {
      content: {
        'application/json': {
          /** @description The uuid of the patient */
          patient_id: components['schemas']['Uuid']
          /** @description The uuid of the provider */
          provider_id: components['schemas']['Uuid']
          /**
           * Format: date-time
           * @description The start time of the slot to book, as returned by GET /v1/providers/slots (start_time_iso). Must be in UTC.
           */
          appointment_slot: string
          appointment_details: {
            /** @description Whether the appointment is in person or virtual */
            is_virtual: boolean
            /**
             * @description The therapy modality of the appointment. Use "Individual", "Couples", or "Family" for therapy sessions. Use "Psychiatry" for psychiatric appointments. Use "15 min Consult" for brief initial consultations.
             * @enum {string}
             */
            appointment_type: 'Individual' | 'Couples' | 'Family' | '15 min Consult' | 'Psychiatry'
            /** @description The two letter state code where the appointment will take place */
            two_letter_state: string
          }
        }
      }
    }
    PatientCreateRequest: {
      content: {
        'application/json': {
          /** @description The patient's identifier in your system. Returned in the response so you can correlate Rula's patient_id with your own records. */
          partner_patient_id: string
          /** @description The first name of the patient. */
          first_name: string
          /** @description The last name of the patient. */
          last_name: string
          /** @description The phone number for the patient. Must be an SMS number. Must be identical to guardian's if minor */
          phone_number: string
          /**
           * Format: email
           * @description The email for the patient. Must be identical to guardian's if minor
           */
          email: string
          /**
           * Format: date
           * @description The patient's date of birth in ISO 8601 date format (YYYY-MM-DD).
           */
          date_of_birth: string
          /** @description The state the patient resides in */
          location: string
          /** @description The carrier id of the insurance for the patient. Use the id field from GET /v1/insurances. Required when is_self_pay is false. */
          insurance_id?: string
          /** @description The insurance member/subscriber ID. Required when both is_eap_referral and is_self_pay are false. */
          subscriber_id?: string
          /**
           * @description The sex assigned at birth of the patient
           * @enum {string}
           */
          sex_at_birth?: 'Female' | 'Male'
          address?: {
            /** @description Is the address given the patient home address */
            is_home_address?: boolean
            /** @description The address street of the patient */
            street?: string
            /** @description The address apt suite of the patient */
            apt_suite?: string
            /** @description The address city of the patient */
            city?: string
            /** @description The address state of the patient */
            state?: string
            /** @description The address zip code of the patient */
            zip_code?: string
          }
          /** @description Guardian information that is required if patient is a minor */
          guardian?: {
            first_name: string
            last_name: string
            /** Format: email */
            email: string
            phone_number: string
          }
          /** @description The types of care the patient is seeking. Determines what appointment types can be booked for this patient. */
          care_types: ('Individual' | 'Couples' | 'Family' | 'Psychiatry')[]
          /**
           * @description Whether the patient will use self-pay instead of insurance. When false, insurance_id is required.
           * @default false
           */
          is_self_pay?: boolean
          /** @description Whether the patient is using an Employee Assistance Program (EAP). When false and is_self_pay is also false, subscriber_id is required. */
          is_eap_referral: boolean
          employee_assistance_program?: {
            /** @description The EAP authorization number */
            authorization_number: string
            /** @description The remaining EAP authorized sessions required for session limited EAPs */
            number_of_authorized_sessions?: number
            /**
             * Format: date
             * @description The expiration date of the EAP required for time limited EAPs
             */
            authorized_session_expiry_date?: string
            /** @description Optionally provide an insurance to be used after EAP is used up. Cannot be another EAP insurance. */
            upcoming_insurance?: {
              /** @description The carrier id of the insurance for the patient */
              insurance_id: string
              /** @description Subscriber id of the insurance */
              subscriber_id: string
            }
          }
        } & (unknown & unknown & unknown)
      }
    }
    ProvidersSearchRequest: {
      content: {
        /**
         * @example {
         *       "two_letter_state": "CA",
         *       "insurance": "Aetna",
         *       "availability": {
         *         "sun": [
         *           [
         *             0,
         *             8
         *           ],
         *           [
         *             16,
         *             20
         *           ]
         *         ],
         *         "mon": [
         *           [
         *             9,
         *             17
         *           ]
         *         ],
         *         "tue": [
         *           [
         *             9,
         *             17
         *           ]
         *         ],
         *         "wed": [
         *           [
         *             9,
         *             17
         *           ]
         *         ],
         *         "thu": [
         *           [
         *             9,
         *             17
         *           ]
         *         ],
         *         "fri": [
         *           [
         *             9,
         *             17
         *           ]
         *         ],
         *         "sat": [],
         *         "time_zone": "America/Los_Angeles"
         *       },
         *       "absolute_availability": [
         *         [
         *           "2026-01-01T00:00:00Z",
         *           "2026-01-01T23:59:59Z"
         *         ],
         *         [
         *           "2026-01-02T00:00:00Z",
         *           "2026-01-02T23:59:59Z"
         *         ]
         *       ]
         *     }
         */
        'application/json': {
          /**
           * @description The maximum number of providers to return, between 1 and 50
           * @default 50
           */
          limit?: number
          /** @description Required. The two-letter state the provider is credentialed in (e.g., "CA", "NY"). */
          two_letter_state: string
          /**
           * @description The category of care to filter providers by. "therapy" returns therapists; "psychiatry" returns prescribers. Defaults to "therapy" if omitted.
           * @default therapy
           * @enum {string}
           */
          care_category?: 'therapy' | 'psychiatry'
          /** @description Insurance network accepted by the provider. Must match the network_name value returned from the GET /insurances endpoint. The value is case-insensitive. */
          insurance?: string
          /**
           * @description The coverage type of the insurance accepted by the provider
           * @enum {string}
           */
          coverage_type?:
            | 'commercial'
            | 'medicare_advantage'
            | 'medicare_ffs'
            | 'medicaid'
            | 'HMO'
            | 'eap'
          /**
           * @description The genders the provider identifies with
           * @enum {string}
           */
          gender?:
            | 'Agender'
            | 'Bigender'
            | 'Cis'
            | 'Female'
            | 'Gender fluid'
            | 'Male'
            | "My gender isn't listed"
            | 'Non-binary'
            | 'Prefer not to respond'
            | 'Trans'
          /**
           * @description The races or ethnicities the provider identifies with
           * @enum {string}
           */
          race?:
            | 'American Indian or Alaska Native'
            | 'Asian'
            | 'Biracial or Multiracial'
            | 'Black or African American'
            | 'Caucasian or White'
            | 'Hispanic or Latinx'
            | 'Middle Eastern'
            | 'Native Hawaiian or Other Pacific Islander'
            | 'Other'
            | 'Prefer Not to Respond'
            | 'South East Asian'
          /**
           * @description The languages spoken by the provider
           * @enum {string}
           */
          language?:
            | 'Afrikaans'
            | 'Arabic'
            | 'Armenian'
            | 'ASL'
            | 'Bengali'
            | 'Bosnian'
            | 'Cantonese'
            | 'Chinese'
            | 'Czech'
            | 'Dutch'
            | 'English'
            | 'Farsi'
            | 'Filipino'
            | 'French'
            | 'German'
            | 'Greek'
            | 'Haitian Creole'
            | 'Hebrew'
            | 'Hindi'
            | 'Hmong'
            | 'Hungarian'
            | 'Indonesian'
            | 'Iranian'
            | 'Italian'
            | 'Japanese'
            | 'Javanese'
            | 'Korean'
            | "My selection isn't listed"
            | 'Norwegian'
            | 'Other'
            | 'Patois'
            | 'Polish'
            | 'Portuguese'
            | 'Punjabi'
            | 'Romanian'
            | 'Russian'
            | 'Spanish'
            | 'Swahili'
            | 'Swedish'
            | 'Thai'
            | 'Turkish'
            | 'Ukrainian'
            | 'Urdu'
            | 'Vietnamese'
            | 'Yoruba'
          /**
           * @description The specializations the provider has
           * @enum {string}
           */
          specialization?:
            | 'Addiction'
            | 'ADHD'
            | 'Adoption'
            | 'Aging'
            | 'Alcohol Use'
            | "Alzheimer's"
            | 'Anger Management'
            | 'Antisocial Personality'
            | 'Anxiety'
            | "Autism or Asperger's Syndrome"
            | 'Behavioral Issues'
            | 'Bipolar Disorder'
            | 'Borderline Personality'
            | 'Career Counseling'
            | 'Child Abuse or Neglect'
            | 'Chronic Illness'
            | 'Chronic Impulsivity'
            | 'Chronic Pain'
            | 'Chronic Relapse'
            | 'Codependency'
            | 'Coping Skills'
            | 'Cultural Stress'
            | 'Depersonalization/Derealization (DPDR)'
            | 'Depression'
            | 'Developmental Disorders'
            | 'Dissociative Disorders'
            | 'Divorce'
            | 'Domestic Violence'
            | 'Drug Abuse'
            | 'Eating Disorders'
            | 'Family Conflict'
            | 'Gambling'
            | 'Gender Identity'
            | 'Grief'
            | 'Hoarding'
            | 'Impulse Control Disorders'
            | 'Impulsivity'
            | 'Infertility'
            | 'Infidelity'
            | 'Intellectual Disability'
            | 'Internet Addiction'
            | 'Job Stress'
            | 'Learning Disabilities'
            | 'Legal Stress'
            | 'LGBTQIA+'
            | 'Life Transitions'
            | "Men's Issues"
            | 'Military and Veterans'
            | 'Mood Disorders'
            | 'Obsessive-Compulsive (OCD)'
            | 'Older Adult'
            | 'Older Adults'
            | 'Oppositional Defiance'
            | 'Panic Attacks'
            | 'Parenting'
            | 'Peer Relationships'
            | 'Personality Disorders'
            | 'Pregnancy, Prenatal, Postpartum'
            | 'Psychosis'
            | 'Racial Identity'
            | 'Racial Trauma'
            | 'Relapse Prevention'
            | 'Relationship Issues'
            | 'Schizophrenia'
            | 'School Issues'
            | 'Self Esteem'
            | 'Self-Harming'
            | 'Sex Therapy'
            | 'Sexual Abuse'
            | 'Sexual Addiction'
            | 'Sleep or Insomnia'
            | 'Spirituality'
            | 'Sports Performance'
            | 'Stress'
            | 'Substance Use'
            | 'Suicidal Ideation'
            | 'Thought Disorders'
            | 'Transgender Issues'
            | 'Trauma and PTSD'
            | 'Traumatic Brain Injury'
            | 'Video Game Addiction'
            | 'Weight Loss'
            | "Women's Issues"
          /**
           * @description The therapeutic modalities the provider practices
           * @enum {string}
           */
          modality?:
            | 'Accelerated Experiential Dynamic Psychotherapy'
            | 'Accelerated Experiential Dynamic Psychotherapy (AEDP)'
            | 'Acceptance and Commitment (ACT)'
            | 'Art Therapy'
            | 'Attachment-based'
            | 'Behavioral Activation'
            | 'Biofeedback'
            | 'Brainspotting'
            | 'Child/Parent Psychotherapy'
            | 'Christian Counseling'
            | 'Cognitive Behavioral (CBT)'
            | 'Cognitive Processing (CPT)'
            | 'Cognitive Processing Therapy (CPT)'
            | 'Collaborative Assessment and Management of Suicidality (CAMS)'
            | 'Collaborative Assessment & Management of Suicidality (CAMS)'
            | 'Compassion Focused'
            | 'Compassion Focused Therapy'
            | 'Complicated Grief Therapy (CGT)'
            | 'Dance/Movement Therapy'
            | 'Dialectical (DBT)'
            | 'EMDR'
            | 'Emotionally Focused Therapy (EFT)'
            | 'Existential Therapy'
            | 'Experiential Therapy'
            | 'Exposure and Response Prevention (ERP)'
            | 'Exposure Response Prevention'
            | 'Expressive Arts'
            | 'Gestalt'
            | 'Gottman Method'
            | 'Humanistic'
            | 'Humanistic Therapy'
            | 'Imago Relationship Therapy'
            | 'Internal Family Systems (IFS)'
            | 'Interpersonal'
            | 'Interpersonal Therapy (IPT)'
            | 'Mindfulness-Based'
            | 'Moral Reconation Therapy (MRT)'
            | 'Motivational Interviewing'
            | 'Multidimensional Family Therapy'
            | 'Multidimensional Family Therapy (MDFT)'
            | 'Music Therapy'
            | 'Narrative'
            | 'Narrative Therapy'
            | 'Neurofeedback'
            | 'Object Relations'
            | 'Parent-Child Interaction (PCIT)'
            | 'Parent-Child Interaction Therapy (PCIT)'
            | 'Play Therapy'
            | 'Prolonged Exposure (PE)'
            | 'Prolonged Exposure Therapy'
            | 'Psychoanalytic'
            | 'Psychobiological Approach Couples Therapy (PACT)'
            | 'Psychobiological Approach to Couples Therapy (PACT)'
            | 'Psychodynamic'
            | 'Psychodynamic Therapy'
            | 'Rational Emotive Behavior (REBT)'
            | 'Rational Emotive Behavior Therapy (REBT)'
            | 'Reality Therapy'
            | 'Sandplay'
            | 'Schema Therapy'
            | 'Sex Therapy'
            | 'Solution Focused Brief (SFBT)'
            | 'Somatic'
            | 'Somatic Therapy'
            | 'Structural Family Therapy'
            | 'Trauma Focused'
            | 'Trauma Focused Dialectical (DBT)'
            | 'Trust-Based Relational Intervention'
            | 'Trust-Based Relational Intervention (TBRI)'
          /** @description Criteria of patients the provider is willing to see */
          willing_to_see?:
            | 'adults'
            | 'children'
            | 'minors'
            | 'preteen'
            | 'individuals'
            | 'couples'
            | 'families'
          /**
           * @description The types of locations where the provider offers service
           * @enum {string}
           */
          location_type?: 'in_person' | 'telemedicine'
          /** @description Filter providers by distance from a geographic location. Useful for finding in-person providers near a patient's address. */
          proximity?: {
            /** @description Latitude of the search center */
            lat: number
            /** @description Longitude of the search center */
            long: number
            /** @description Maximum distance in miles from the search center */
            max_miles: number
          }
          /** @description Filter providers to those who have availability within the specified weekly schedule (e.g. weekday mornings). All days of the week and time_zone are required. Cannot be specified if absolute_availability is provided. */
          availability?: {
            /** @description An array of hour spans (start hour 0-23, end hour 1-24) */
            sun: number[][]
            /** @description An array of hour spans (start hour 0-23, end hour 1-24) */
            mon: number[][]
            /** @description An array of hour spans (start hour 0-23, end hour 1-24) */
            tue: number[][]
            /** @description An array of hour spans (start hour 0-23, end hour 1-24) */
            wed: number[][]
            /** @description An array of hour spans (start hour 0-23, end hour 1-24) */
            thu: number[][]
            /** @description An array of hour spans (start hour 0-23, end hour 1-24) */
            fri: number[][]
            /** @description An array of hour spans (start hour 0-23, end hour 1-24) */
            sat: number[][]
            /** @description IANA timezone name (e.g., 'America/Los_Angeles') */
            time_zone: string
          }
          /** @description An array of [start, end] ISO 8601 datetime pairs representing specific date-time windows the provider must be available within. Cannot be specified if availability is provided. */
          absolute_availability?: string[][]
        }
      }
    }
  }
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  insurancesIndex: {
    parameters: {
      query?: {
        /** @description Two-letter state code (e.g. CA, NY) to filter insurances by state. If omitted, insurances for all states are returned. */
        state?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['InsurancesIndexResponse']
      /** @description Unauthorized, invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InternalServerError']
        }
      }
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InternalServerError']
        }
      }
    }
  }
  providersShow: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The uuid of the provider to retrieve
         * @example 9c823227-dbe1-408c-9e71-0685817e3410
         */
        uuid: components['schemas']['Uuid']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['ProvidersShowResponse']
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Unauthorized, invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InternalServerError']
        }
      }
    }
  }
  providersSearch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['ProvidersSearchRequest']
    responses: {
      200: components['responses']['ProvidersSearchResponse']
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Unauthorized, invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InternalServerError']
        }
      }
    }
  }
  providersSlots: {
    parameters: {
      query: {
        /** @description The unique Rula-provided identifier for the provider. */
        provider_uuid: components['schemas']['Uuid']
        /** @description Two-letter state code (e.g., "CA" for California). */
        two_letter_state: string
        /** @description A [start, end] pair of ISO 8601 datetime strings defining the window to fetch slots within. The first element is the start (inclusive) and the second is the end (inclusive). Filters by slot start time. When omitted, defaults to 25 hours from now through 28 days out. No maximum window is enforced. */
        start_time_range?: string[]
        /** @description Array of location types to filter appointment slots by (in-person vs virtual). */
        location_type: ('in_person' | 'telemedicine')[]
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['ProvidersSlotsResponse']
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Unauthorized, invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InternalServerError']
        }
      }
    }
  }
  patientCreate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['PatientCreateRequest']
    responses: {
      200: components['responses']['PatientCreateResponse']
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Unauthorized, invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unprocessable Entity - Business logic validation failure (e.g., EAP with psychiatry not supported, patient is a minor) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json':
            | components['schemas']['RequestValidationError']
            | components['schemas']['UnprocessableEntityError']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InternalServerError']
        }
      }
      /** @description Bad Gateway - External service failure (e.g., patient identification failed, insurance validation failed) */
      502: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BadGatewayError']
        }
      }
    }
  }
  patientAppointments: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The uuid of the patient to retrieve appointments for
         * @example 9c823227-dbe1-408c-9e71-0685817e3410
         */
        uuid: components['schemas']['Uuid']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['PatientAppointmentsResponse']
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Unauthorized, invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found Error */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotFoundError']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InternalServerError']
        }
      }
    }
  }
  appointmentsShow: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The uuid of the appointment to retrieve
         * @example 9c823227-dbe1-408c-9e71-0685817e3410
         */
        uuid: components['schemas']['Uuid']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['AppointmentShowResponse']
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Unauthorized, invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found Error */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotFoundError']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InternalServerError']
        }
      }
    }
  }
  appointmentsCancel: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The uuid of the appointment to cancel
         * @example 9c823227-dbe1-408c-9e71-0685817e3410
         */
        uuid: components['schemas']['Uuid']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['AppointmentCancelRequest']
    responses: {
      200: components['responses']['AppointmentShowResponse']
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Unauthorized, invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found Error */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotFoundError']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json':
            | components['schemas']['RequestValidationError']
            | components['schemas']['UnprocessableEntityError']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InternalServerError']
        }
      }
    }
  }
  appointmentsCreate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['AppointmentsCreateRequest']
    responses: {
      200: components['responses']['AppointmentsCreateResponse']
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RequestValidationError']
        }
      }
      /** @description Unauthorized, invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found Error */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotFoundError']
        }
      }
      /** @description Not Acceptable */
      406: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotAcceptableError']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConflictError']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json':
            | components['schemas']['RequestValidationError']
            | components['schemas']['UnprocessableEntityError']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InternalServerError']
        }
      }
    }
  }
}
