// Provider search filter options.
// Human-readable labels shown in the UI; the BFF (apps/api/src/filterMaps.ts)
// maps these to the API's short lowercase enum keys before forwarding to the
// partner API.

export const LANGUAGE_OPTIONS = [
  'English',
  'Spanish',
  'Mandarin',
  'Cantonese',
  'Tagalog',
  'Vietnamese',
  'Arabic',
  'French',
  'Korean',
  'Russian',
  'Hindi',
  'Portuguese',
  'Hmong',
  'Farsi',
  'Armenian',
  'ASL',
  'Bengali',
  'Punjabi',
  'Japanese',
  'Urdu',
  'Haitian Creole',
  'Polish',
  'Italian',
  'German',
  'Bosnian',
  'Ukrainian',
  'Romanian',
  'Greek',
  'Turkish',
  'Hebrew',
  'Swahili',
  'Yoruba',
  'Thai',
  'Indonesian',
  'Javanese',
  'Dutch',
  'Hungarian',
  'Czech',
  'Swedish',
  'Norwegian',
  'Afrikaans',
  'Patois',
  'Iranian',
  'Other',
  "My selection isn't listed",
] as const

export const GENDER_OPTIONS = [
  'Female',
  'Male',
  'Trans',
  'Non-binary',
  'Gender fluid',
  'Agender',
  'Bigender',
  'Cis',
  "My gender isn't listed",
  'Prefer not to respond',
] as const

export const RACE_OPTIONS = [
  'American Indian or Alaska Native',
  'Asian',
  'Biracial or Multiracial',
  'Black or African American',
  'Caucasian or White',
  'Hispanic or Latinx',
  'Middle Eastern',
  'Native Hawaiian or Other Pacific Islander',
  'South East Asian',
  'Other',
  'Prefer Not to Respond',
] as const

export const SPECIALIZATION_OPTIONS = [
  'Anxiety',
  'Depression',
  'Trauma and PTSD',
  'Relationship Issues',
  'Grief',
  'ADHD',
  'Bipolar Disorder',
  'Eating Disorders',
  'LGBTQIA+',
  'Life Transitions',
  'Addiction',
  'Anger Management',
  'Coping Skills',
  'Family Conflict',
  'Self Esteem',
  'Stress',
  'Sleep or Insomnia',
  'Chronic Illness',
  'Chronic Pain',
  'Pregnancy, Prenatal, Postpartum',
] as const

export const FAITH_OPTIONS = [
  'Christian',
  'Jewish',
  'Muslim',
  'Buddhist',
  'Hindu',
  'Sikh',
  'Agnostic',
  'Atheist',
  'Interfaith',
  'Non-denominational',
  'Spiritual',
  'Mormon',
  "Jehovah's Witness",
  'Pagan',
  'Taoist',
  'Unitarian Universalism',
  'Wiccan',
  'Satanist',
  'Other',
  'Prefer not to respond',
] as const

export const ALLYSHIP_OPTIONS = [
  'LGBTQIA+',
  'BIPOC',
  'Military/Veterans',
  'Transgender',
  'Gay',
  'Lesbian',
  'Queer',
  'Non-Binary',
  'Intersex',
  'Racial Justice',
  'Body Positivity',
  'Recovery/12 Step Friendly',
  'First Gen American/Immigrant Parents',
  'Police/Fire/First Responders',
  'Aviation Professionals',
  'Educators',
  'Blind',
  'Deaf',
  'Cancer',
  'HIV/AIDS',
  'Immune-Disorders',
  'Little Person',
  'Open Relationships/Non-Monogamy',
  'Sex-Positive/Kink',
  'Sex Worker',
  'Single Mother',
  'Vegan',
] as const

export const LICENSE_OPTIONS = [
  'LCSW',
  'LMFT',
  'LPC',
  'LMHC',
  'LP',
  'MD',
  'NP',
  'DO',
  'ACD-LAC',
  'CSW-PIP',
  'IMFT',
  'LCMFT',
  'LCMHC',
  'LCP',
  'LCPC',
  'LCSW-C',
  'LICSW',
  'LIMHP',
  'LISW',
  'LISW-CP',
  'LISW-S',
  'LMSW-C',
  'LPC-I',
  'LPCC',
  'LPCC-S',
  'LPCMH',
  'LPCS',
  'LSCSW',
] as const
